import Foundation

/// Directory names that mark developer-tool dependency trees, caches, or
/// build output.
///
/// The risk this guards against is different from `BundleProtection`'s:
/// deleting a file out of a signed `.app` breaks a code signature, but
/// deleting a duplicate file out of a project-local `node_modules` breaks
/// that specific project's build until it's reinstalled - and unlike a
/// global package-manager cache (`~/.npm`, `~/Library/Caches/npm`, both of
/// which regenerate cleanly if a file goes missing), neither
/// `DuplicateDetector` nor `LargeFileFinder` has any way to tell an active
/// `node_modules` from an abandoned one. The same package (e.g. `lodash`)
/// is also routinely installed byte-identically across a dozen unrelated
/// projects, which makes this the single biggest source of noisy,
/// low-value duplicate reports on a developer's Mac.
///
/// Two ways to apply this list, for two different call sites:
/// - `isDeveloperArtifactDirectory(_:)` checks a single directory *name*,
///   used by `DuplicateDetector`/`LargeFileFinder`'s tree walk
///   (`DuplicateScanOptions.includeDeveloperArtifacts` /
///   `LargeFileFilter.includeDeveloperArtifacts`) to skip descending into
///   matching directories entirely - the candidate never gets stat'd or
///   hashed. Still available for callers that want faster scans by never
///   examining these directories at all (e.g. a future CLI tool).
/// - `pathContainsDeveloperArtifact(_:)` checks a full *path* for any
///   matching component - for a caller that scans with
///   `includeDeveloperArtifacts: true` and wants to filter or label results
///   after the fact rather than skip them at scan time.
public enum DeveloperArtifactFolders {
    private static let names: Set<String> = [
        // Dependency / install trees
        "node_modules", "bower_components",
        // Package manager caches and stores
        ".npm", ".pnpm-store", ".yarn", ".cargo", ".rustup", ".gradle", ".m2",
        // Language-specific virtual environments / bytecode caches
        ".venv", "venv", "__pycache__", ".tox",
        // Xcode / SwiftPM / CocoaPods build output
        "deriveddata", ".build", "pods",
        // Cargo (Rust) and Maven (Java) both use a project-local "target"
        // directory for build output - compiled object files, dependency
        // artifacts, build-script binaries - entirely regenerated by
        // `cargo build` / `mvn package`. This is included by name alone
        // (not scoped to, say, "target" only under a Cargo.toml sibling)
        // because a directory genuinely named "target" for an unrelated
        // reason is rare enough that the reveal toggle is a fine fallback,
        // and the alternative - leaving it out over a hypothetical false
        // positive - left real Cargo build output as the dominant source
        // of noise in practice (a single Rust project's `target/debug/`
        // routinely produces dozens of near-identical multi-megabyte
        // build artifacts).
        "target",
        // Version control internals - not "duplicates" in any meaningful
        // sense, and individual objects inside a VCS store aren't safe to
        // delete piecemeal without corrupting the repository.
        ".git", ".svn", ".hg",
    ]

    public static func isDeveloperArtifactDirectory(_ name: String) -> Bool {
        names.contains(name.lowercased())
    }

    /// True when any component of `path` is a developer-artifact
    /// directory name.
    public static func pathContainsDeveloperArtifact(_ path: String) -> Bool {
        (path as NSString).pathComponents.contains { isDeveloperArtifactDirectory($0) }
    }
}
